### ISSUE TITLE
Citations are inserted without parentheses

### ISSUE THREAD

**Issue by merges** [Zotero-ODF-Scan/zotero-odf-scan#18]
Using the standalone version of Zotero Mac (4.0.28.8) and most recent scannable cite. The following:

`often used to describe someone involved in an episode of care { | Greene, & Partridge, 2007 | | |zu:1546826:B3VCFIIS} and playing`

is scanned, with the citation turned into

`often used to describe someone involved in an episode of care Greene, & Partridge, 2007 and playing`

Missing parentheses around the (citation). Also, those extra commas are strange but I can get rid of them with search and replace. Any thoughts on whether this is a bug or something I can fix on my end?

**Comment by fbennett** [comment]
Does the citation form improve when the document is refreshed?

**Comment by adam3smith** [comment]
continued (and I'm pretty sure answered) here: https://forums.zotero.org/discussion/57161/scannable-cite-replacements-missing-parentheses/#Comment_247576
