### ISSUE TITLE
Locator for Books

### ISSUE THREAD

**Issue by paultroop** [Zotero-ODF-Scan/zotero-odf-scan#25]
I've also commented on Frank's Juris version, but could there be a locator for books please, i.e. Aristotle, Metaethics, Book VI?

**Comment by fbennett** [comment]
The repository under Juris-M is the plugin. It's a submodule of the main project here. I answered over there, but for the benefit of anyone driving by, Book can be set as a locator term using its abbreviation, "bk." The full list of labels [is here](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#locator-terms).

**Comment by paultroop** [comment]
Thanks Frank! I was going by the following list that does not contain book: https://zotero-odf-scan.github.io/zotero-odf-scan/

**Comment by fbennett** [comment]
Thanks for pointing that out. We need to make an update there.
